<x-app-layout>
    <x-slot name="header">
        <div class="flex items-center justify-between">
            <div>
                <a href="{{ route('dashboard') }}"
                   class="text-sm font-medium text-slate-500 hover:text-emerald-600">
                    ← RevenueTwin8
                </a>

                <h2 class="mt-1 text-xl font-semibold text-slate-900">
                    Relay8
                </h2>
            </div>

            <span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-semibold text-emerald-700">
                Dynamic Approval Gateway
            </span>
        </div>
    </x-slot>

    <div class="min-h-screen bg-slate-950 py-10">
        <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">

            @if (session('success'))
                <div class="mb-6 rounded-2xl border border-emerald-500/30 bg-emerald-500/10 px-5 py-4 text-sm font-medium text-emerald-300">
                    {{ session('success') }}
                </div>
            @endif

            <div class="rounded-3xl border border-emerald-500/20 bg-gradient-to-br from-emerald-950/40 via-slate-900 to-slate-950 p-8">
                <div class="flex flex-wrap items-center justify-between gap-8">
                    <div>
                        <p class="text-xs font-semibold uppercase tracking-[0.25em] text-emerald-400">
                            Decision Control
                        </p>

                        <h1 class="mt-3 text-4xl font-bold text-white">
                            Review before execution
                        </h1>

                        <p class="mt-4 max-w-2xl leading-7 text-slate-400">
                            Recommendations generated by RevenueTwin8 simulations enter
                            this live approval queue before graph8 execution.
                        </p>
                    </div>

                    <div class="grid grid-cols-3 gap-3">
                        <div class="rounded-2xl border border-amber-500/20 bg-amber-500/5 px-5 py-4 text-center">
                            <p class="text-xs uppercase tracking-wider text-amber-400">
                                Pending
                            </p>

                            <p class="mt-2 text-3xl font-bold text-white">
                                {{ $pendingCount }}
                            </p>
                        </div>

                        <div class="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 px-5 py-4 text-center">
                            <p class="text-xs uppercase tracking-wider text-cyan-400">
                                Approved
                            </p>

                            <p class="mt-2 text-3xl font-bold text-white">
                                {{ $approvedCount }}
                            </p>
                        </div>

                        <div class="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 px-5 py-4 text-center">
                            <p class="text-xs uppercase tracking-wider text-emerald-400">
                                Executed
                            </p>

                            <p class="mt-2 text-3xl font-bold text-white">
                                {{ $executedCount }}
                            </p>
                        </div>
                    </div>
                </div>
            </div>

            <div class="mt-8 grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">

                <section class="rounded-3xl border border-white/10 bg-slate-900 p-7">
                    <div class="flex items-center justify-between">
                        <div>
                            <p class="text-xs font-semibold uppercase tracking-[0.25em] text-emerald-400">
                                Approval Queue
                            </p>

                            <h2 class="mt-3 text-2xl font-bold text-white">
                                Recommended actions
                            </h2>
                        </div>

                        <span class="rounded-full bg-slate-800 px-3 py-1 text-xs text-slate-400">
                            {{ $recommendations->count() }} Total
                        </span>
                    </div>

                    <div class="mt-7 space-y-5">
                        @forelse ($recommendations as $recommendation)
                            <article class="rounded-2xl border border-white/10 bg-slate-950 p-6">
                                <div class="flex flex-wrap items-start justify-between gap-4">
                                    <div class="max-w-2xl">
                                        <div class="flex flex-wrap items-center gap-2">
                                            <span class="rounded-full bg-violet-500/10 px-3 py-1 text-xs font-semibold text-violet-300">
                                                {{ ucfirst($recommendation->source_module) }}
                                            </span>

                                            <span class="text-xs text-slate-600">
                                                {{ $recommendation->created_at->diffForHumans() }}
                                            </span>
                                        </div>

                                        <h3 class="mt-4 text-xl font-semibold text-white">
                                            {{ $recommendation->title }}
                                        </h3>

                                        <p class="mt-3 text-sm leading-6 text-slate-400">
                                            {{ $recommendation->summary }}
                                        </p>
                                    </div>

                                    <span class="rounded-full px-3 py-1 text-xs font-semibold
                                        {{ $recommendation->status === 'pending'
                                            ? 'bg-amber-500/10 text-amber-300'
                                            : ($recommendation->status === 'approved'
                                                ? 'bg-cyan-500/10 text-cyan-300'
                                                : ($recommendation->status === 'executed'
                                                    ? 'bg-emerald-500/10 text-emerald-300'
                                                    : 'bg-rose-500/10 text-rose-300')) }}"
                                    >
                                        {{ ucfirst($recommendation->status) }}
                                    </span>
                                </div>

                                <div class="mt-5 rounded-xl border border-white/5 bg-slate-900 p-4">
                                    <div class="flex items-center justify-between gap-4">
                                        <div>
                                            <p class="text-xs uppercase tracking-wider text-slate-600">
                                                graph8 Action Type
                                            </p>

                                            <p class="mt-1 text-sm font-semibold text-emerald-300">
                                                {{ $recommendation->action_type }}
                                            </p>
                                        </div>

                                        @if ($recommendation->simulation)
                                            <div class="text-right">
                                                <p class="text-xs uppercase tracking-wider text-slate-600">
                                                    Simulation Score
                                                </p>

                                                <p class="mt-1 text-sm font-semibold text-white">
                                                    {{ $recommendation->simulation->score ?? 'N/A' }}
                                                </p>
                                            </div>
                                        @endif
                                    </div>

                                    @if (! empty($recommendation->action_payload))
                                        <div class="mt-4 border-t border-white/5 pt-4">
                                            <p class="text-xs uppercase tracking-wider text-slate-600">
                                                Dynamic Action Payload
                                            </p>

                                            <pre class="mt-2 overflow-x-auto whitespace-pre-wrap text-xs leading-5 text-slate-400">{{ json_encode($recommendation->action_payload, JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES) }}</pre>
                                        </div>
                                    @endif
                                </div>

                                @if ($recommendation->status === 'pending')
                                    <div class="mt-5 flex flex-wrap gap-3">
                                        <form
                                            method="POST"
                                            action="{{ route('relay.approve', $recommendation) }}"
                                        >
                                            @csrf
                                            @method('PATCH')

                                            <button
                                                type="submit"
                                                class="rounded-xl bg-emerald-500 px-5 py-2.5 text-sm font-semibold text-slate-950 transition hover:bg-emerald-400"
                                            >
                                                Approve Action
                                            </button>
                                        </form>

                                        <form
                                            method="POST"
                                            action="{{ route('relay.reject', $recommendation) }}"
                                        >
                                            @csrf
                                            @method('PATCH')

                                            <button
                                                type="submit"
                                                class="rounded-xl border border-rose-500/30 bg-rose-500/10 px-5 py-2.5 text-sm font-semibold text-rose-300 transition hover:bg-rose-500/20"
                                            >
                                                Reject
                                            </button>
                                        </form>
                                    </div>
                                @elseif ($recommendation->status === 'approved')
                                    <div class="mt-5 flex flex-wrap items-center justify-between gap-4 rounded-xl border border-cyan-500/20 bg-cyan-500/5 p-4">
                                        <div>
                                            <p class="text-sm font-semibold text-cyan-300">
                                                Approved for graph8 execution
                                            </p>

                                            <p class="mt-1 text-xs text-slate-500">
                                                Approved {{ $recommendation->approved_at?->diffForHumans() }}
                                            </p>
                                        </div>

                                        <span class="rounded-lg bg-slate-800 px-4 py-2 text-xs font-semibold text-slate-400">
                                            API connection pending
                                        </span>
                                    </div>
                                @elseif ($recommendation->status === 'executed')
                                    <div class="mt-5 rounded-xl border border-emerald-500/20 bg-emerald-500/5 p-4">
                                        <p class="text-sm font-semibold text-emerald-300">
                                            Successfully executed through graph8
                                        </p>

                                        <p class="mt-1 text-xs text-slate-500">
                                            {{ $recommendation->executed_at?->format('M d, Y — h:i A') }}
                                        </p>
                                    </div>
                                @endif
                            </article>
                        @empty
                            <div class="rounded-2xl border border-dashed border-slate-700 bg-slate-950/60 p-10 text-center">
                                <div class="mx-auto flex h-14 w-14 items-center justify-center rounded-2xl bg-slate-800 text-2xl text-emerald-400">
                                    ⚡
                                </div>

                                <h3 class="mt-4 font-semibold text-white">
                                    Approval queue is empty
                                </h3>

                                <p class="mx-auto mt-2 max-w-md text-sm leading-6 text-slate-500">
                                    Complete a RevenueTwin8 simulation to dynamically
                                    generate a recommended graph8 action.
                                </p>
                            </div>
                        @endforelse
                    </div>
                </section>

                <section class="space-y-6">
                    <div class="rounded-3xl border border-white/10 bg-slate-900 p-7">
                        <p class="text-xs font-semibold uppercase tracking-[0.25em] text-slate-500">
                            Execution Pipeline
                        </p>

                        <div class="mt-6 space-y-4">
                            <div class="flex items-center gap-4 rounded-2xl bg-slate-950 p-4">
                                <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-violet-500/15 font-bold text-violet-300">
                                    1
                                </div>

                                <div>
                                    <p class="font-semibold text-white">Simulation result</p>
                                    <p class="text-xs text-slate-500">Recommendation enters Relay8</p>
                                </div>
                            </div>

                            <div class="flex items-center gap-4 rounded-2xl bg-slate-950 p-4">
                                <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-amber-500/15 font-bold text-amber-300">
                                    2
                                </div>

                                <div>
                                    <p class="font-semibold text-white">Human approval</p>
                                    <p class="text-xs text-slate-500">Approve or reject dynamic action</p>
                                </div>
                            </div>

                            <div class="flex items-center gap-4 rounded-2xl bg-slate-950 p-4">
                                <div class="flex h-10 w-10 items-center justify-center rounded-xl bg-emerald-500/15 font-bold text-emerald-300">
                                    3
                                </div>

                                <div>
                                    <p class="font-semibold text-white">graph8 execution</p>
                                    <p class="text-xs text-slate-500">Send approved API payload</p>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="rounded-3xl border border-white/10 bg-slate-900 p-7">
                        <div class="flex items-center justify-between">
                            <div>
                                <p class="text-sm font-semibold text-white">
                                    graph8 API
                                </p>

                                <p class="mt-1 text-xs text-slate-500">
                                    Execution connection
                                </p>
                            </div>

                            <span class="rounded-full bg-amber-500/10 px-3 py-1 text-xs font-semibold text-amber-300">
                                Awaiting Hackathon Credentials
                            </span>
                        </div>
                    </div>
                </section>

            </div>
        </div>
    </div>
</x-app-layout>